attach_duration_msec: null
attach_pid: null
bench_only: false
config_dir: /opt/venv/lib/python3.12/site-packages/_rocm_profiler/libexec/rocprofiler-compute/rocprof_compute_soc/analysis_configs
device: 0
dispatch:
- '1'
experimental: false
filter_blocks:
- 2.1.17
- 2.1.18
- 16.1.2
- 17.1.0
format_rocprof_output: rocpd
iteration_multiplexing: null
join_type: grid
kernel:
- Cijk_Alik_Bljk_BBS_BH_Bias_HA_S_SAV_UserArgs_MT256x256x64
kokkos_trace: false
list_available_metrics: false
list_blocks: null
list_metrics: null
list_sets: false
loglevel: 20
membw_analysis: false
mode: profile
name: null
no_native_tool: true
no_roof: true
output_directory: runs/ch3-rpc-one-gemm-memory
pc_sampling: false
pc_sampling_interval: null
pc_sampling_method: stochastic
quiet: false
remaining: python3 -m bench.transformer_block --strategy dp --devices 1 --tokens 2048
  --layers 1 --warmup 10 --repeats 1 --no-freeze --tag ch3-rpc-one-gemm-memory
retain_rocpd_output: false
rocprofiler_sdk_tool_path: /opt/venv/lib/python3.12/site-packages/_rocm_sdk_devel/lib/rocprofiler-sdk/librocprofiler-sdk-tool.so
roof_only: false
set_selected: mem_thruput
spatial_multiplexing: null
specs: false
target: null
torch_trace: false
verbose: 0
